site_name: SCONE
pages:
 - Introduction: index.md
 - SCONE Background: background.md
 - SCONE Host Setup: SCONE_HOSTINSTALLER_README.md
 - SCONE SGX toolchain: SCONE_COMPILER_CONTAINER_README.md
 - SCONE Curated Images: SCONE_Curated_Images.md
 - SCONE Tutorial: SCONE_TUTORIAL.md
 - SCONE Create Image: SCONE_GENERATE_IMAGE.md
 - SCONE Dockerfile: SCONE_Dockerfile.md
 - SCONE Publications:  SCONE_Publications.md
theme: readthedocs
